#!/usr/bin/env bash
#pings an IP address passed as an argument
#if not Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -4 -c 5 "$1"
fi
