#!/usr/bin/env bash
# change ip for localhost and facebook.com on my machine
cp /etc/hosts ~/new_hosts
sed -i 's/127.0.0.1	localhost/127.0.0.2	localhost/g' ~/new_hosts
echo "8.8.8.8	facebook.com" >> ~/new_hosts
cp -f ~/new_hosts /etc/hosts
